### ISSUE TITLE
Invisible function unstable

### ISSUE THREAD

**Issue by Test0rMaik** [tronfamily/Desktop-Wallet#10]
Die App bietet mit dem "Auge" die Möglichkeit, diese mit einem klick zur Uhr zu "verstecken", so dass sie da als Icon gezeigt wird, aber als Fenster geschlossen ist.

Folgender Fehler:
1. Wechsel zu den Settings
2. Wechsel zurück zum Dashboard bzw. Wallet
3. klicken des "Auges"
-> App wird komplett geschlossen.

-> ohne Nutzung der Settings zwischendurch funktioniert es einwandfrei, so dass nach Klicken auf das Icon bei der Uhr die App wieder geöffnet wird

**Comment by tronfamily** [comment]
Fixed
