### ISSUE TITLE
Nach einem Buy auf TronTrade ist die Order History nicht mehr sichtbar

### ISSUE THREAD

**Issue by Ischkur** [tronfamily/Desktop-Wallet#15]
Nach einem Buy auf TronTrade ist die Order History nicht mehr sichtbar. Auch ein Neustart der Applikation hat nichts geholfen. Bei PoniDex ist die History sichtbar, bei TronTrade nicht.

Erwartetes Verhalten:
- Order History wird angezeigt 
- Neue Order ist sichtbar

![image](https://user-images.githubusercontent.com/13943220/72285381-4960a280-3643-11ea-8fdd-ba07907315bb.png)

Die Order ist immer noch offen. Hier noch die Ansicht in TronWalletPlay:
![image](https://user-images.githubusercontent.com/13943220/72285601-bc6a1900-3643-11ea-9285-8b664e68aec1.png)

**Comment by Ischkur** [comment]
Hab das Verhalten nochmals nachvollziehen können.
- Wenn eine offene Order vorhanden ist, wird die Order Liste nicht angezeigt.
- Wenn die Order Canceled / Completed ist, kann man den Token wechseln -> zurück zum ursprünglichen Token -> Dann wird die Liste wieder angezeigt.

**Comment by tronfamily** [comment]
Remove the option "all orders" due to incompatibility of exchanges
