### ISSUE TITLE
Windows Shortcuts (Win -> / Win <-) funktionieren nicht

### ISSUE THREAD

**Issue by Ischkur** [tronfamily/Desktop-Wallet#16]
Ich ordne gerne die Fenster auf meinem Bildschirm mit den Windows Shortcuts: Win Taste + Pfeil nach rechts / links.

Das funktioniert aktuell nicht.

Erwartetes Verhalten:
- Beim Drücken von Windows Taste + Pfeil nach rechts wird das Fenster in der ganzen rechten Hälfte des Bildschirms angezeigt.
- Beim Drücken von Windows Taste + Pfeil nach links wird das Fenster in der ganzen linken Hälfte des Bildschirms angezeigt.

**Comment by tronfamily** [comment]
fixed
