### ISSUE TITLE
Send Trx lädt ersten TRC10 Token

### ISSUE THREAD

**Issue by Ischkur** [tronfamily/Desktop-Wallet#18]
Der Homescreen ist in zwei Teile unterteilt. Links die Auflistung der Tokens (TRC10, TRC20) rechts ist die Funktionalität zum Versenden.
- Wenn ich im rechten Bereich auf den Button "Send TRX" neben dem "Amount available" und dann auf "ALL" klicke, wird im "Amount available" die Verfügbare Menge an TRX angezeigt und der Button zum richtigen Versenden ist mit "SEND TRX" beschriftet.
- Wenn ich das nächste mal auf denselben "Send TRX" Button und danach erneut auf "ALL" klicke, wird die Verfügbare Menge von dem ersten Element in der TRC10 Token Liste geladen. (Beim richtigen Versenden Button steht immer noch "SEND TRX". Im Gegensatz, wenn ich direkt einen Token aus der Liste auswähle.
- Mit jeder Wiederholung des Vorganges wechselt der Betrag wieder zwischen TRX und TRC10 Token.

Was dann im Endeffekt versendet würde, weiss ich nicht. Das versuche ich nicht. ;)

Ich würde erwarten, dass ein Klick auf diesen "Send TRX" Button immer auf TRX wechselt. Unabhängig, was bereits geladen ist.

1.  ![image](https://user-images.githubusercontent.com/13943220/72300287-a5d3ba00-3663-11ea-9940-b96831c32a44.png)
2. BitTorent aus Liste gewählt:
![image](https://user-images.githubusercontent.com/13943220/72300341-cef44a80-3663-11ea-88be-6466908811ee.png)
3. TRX ausgewählt: 
![image](https://user-images.githubusercontent.com/13943220/72300377-e7646500-3663-11ea-9c94-4c4c715c66b7.png)
Hier ist noch die falsche Anzahl von verfügbaren TRX
4. Nochmals Send TRX: 
![image](https://user-images.githubusercontent.com/13943220/72300471-2f838780-3664-11ea-91d4-d40d2621e024.png)
5. Und so weiter...

**Comment by Ischkur** [comment]
Abgesehen davon finde ich es verwirrend, wenn beide Buttons gleich angeschrieben sind. Ich konnte mir zusammenreimen, was wohl die Funktion ist. Ich würde eher select TRX, pick TRX oder sonst was nehmen für diesen Button.

**Comment by tronfamily** [comment]
Fixed
