### ISSUE TITLE
Falsche Wallet auswahl nach Import

### ISSUE THREAD

**Issue by Ischkur** [tronfamily/Desktop-Wallet#19]
Nach einem Import einer schon existierenden Wallet wird diese zwar angelegt aber in der Applikation nicht automatisch ausgewählt. Der Effekt ist dann so, dass auf einmal andere Daten in den Feldern stehen (Nämlich diejenigen, der vor dem Import ausgewählten Wallet.

Erwartetes Verhalten:
- Nach dem Anlegen einer Wallet (egal ob durch Import oder Create) sollte diese neu angelegte Wallet automatisch ausgewählt sein.
- Nice to have wäre eine kurze Bestätigung, dass die Wallet erstellt / gelöscht wurde.

**Comment by tronfamily** [comment]
Fixed
