### ISSUE TITLE
Mehere Icons nach App Minimieren

### ISSUE THREAD

**Issue by Ischkur** [tronfamily/Desktop-Wallet#21]
Ich hab die Applikation minimiert (durchgestrichenes Auge). Danach hatte ich das Icon in der Taskliste doppelt. 
![image](https://user-images.githubusercontent.com/13943220/72385356-9f0a7d00-371f-11ea-952f-9ffdd9491f77.png)

Ausserdem finde ich den Text "Notifyicon1" nicht sehr glücklich gewählt. ;)

**Comment by tronfamily** [comment]
fixed
