### ISSUE TITLE
Distribute Tool - Unable to delete a job and error switching between jobs

### ISSUE THREAD

**Issue by DanielMelo02** [tronfamily/Desktop-Wallet#22]
Distribute Tool

After saving a job there is no way to delete it the "delete" button doesn't work.

![image](https://user-images.githubusercontent.com/44190920/72421393-af067900-3780-11ea-92e7-3f67e686b116.png)

When i added another job and tried to switch job this error apeared.

![image](https://user-images.githubusercontent.com/44190920/72421557-00166d00-3781-11ea-891d-c283cf7932f7.png)

The error details bellow in portuguese sorry:

Consulte o fim desta mensagem para obter detalhes sobre como invocar a depuração 
JIT (just-in-time) em vez desta caixa de diálogo.

************** Texto da excepção **************
System.ArgumentOutOfRangeException: O valor de '-1' não é válido para 'Maximum'. 'Maximum' tem de ser superior ou igual a 0.
Nome do parâmetro: Maximum
   em System.Windows.Forms.ProgressBar.set_Maximum(Int32 value)
   em TRONFamily_DesktopWallet.Form1.BSListBox1_SelectedIndexChanged(Object sender, EventArgs e)
   em System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
   em System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
   em System.Windows.Forms.ListBox.WndProc(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assemblagens carregadas **************
mscorlib
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
System
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
TRON-Family Wallet
    Versão da assemblagem: 1.0.1.0
    Versão Win32: 1.0.1.0
    CodeBase: file:///C:/Users/daniel.melo/AppData/Local/Apps/2.0/OGMV3B8Z.4RX/TQA8EET3.H9M/tron..tion_2ecfac97233d89a0_0001.0000_1cab448ac398cc4a/TRON-Family%20Wallet.exe
----------------------------------------
Microsoft.VisualBasic
    Versão da assemblagem: 10.0.0.0
    Versão Win32: 14.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Windows.Forms.resources
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pt_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
System.Windows.Forms.DataVisualization
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.3815.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.DataVisualization/v4.0_4.0.0.0__31bf3856ad364e35/System.Windows.Forms.DataVisualization.dll
----------------------------------------
System.Windows.Forms.DataVisualization.resources
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.3752.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.DataVisualization.resources/v4.0_4.0.0.0_pt_31bf3856ad364e35/System.Windows.Forms.DataVisualization.resources.dll
----------------------------------------
Accessibility
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
mscorlib.resources
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pt_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Microsoft.VisualBasic.resources
    Versão da assemblagem: 10.0.0.0
    Versão Win32: 14.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic.resources/v4.0_10.0.0.0_pt_b03f5f7f11d50a3a/Microsoft.VisualBasic.resources.dll
----------------------------------------
System.Deployment
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
Device.Net
    Versão da assemblagem: 3.1.0.0
    Versão Win32: 3.1.0.0
    CodeBase: file:///C:/Users/daniel.melo/AppData/Local/Apps/2.0/OGMV3B8Z.4RX/TQA8EET3.H9M/tron..tion_2ecfac97233d89a0_0001.0000_1cab448ac398cc4a/Device.Net.DLL
----------------------------------------
Hid.Net
    Versão da assemblagem: 3.1.0.0
    Versão Win32: 3.1.0.0
    CodeBase: file:///C:/Users/daniel.melo/AppData/Local/Apps/2.0/OGMV3B8Z.4RX/TQA8EET3.H9M/tron..tion_2ecfac97233d89a0_0001.0000_1cab448ac398cc4a/Hid.Net.DLL
----------------------------------------
Ledger.Net
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.0.0.0
    CodeBase: file:///C:/Users/daniel.melo/AppData/Local/Apps/2.0/OGMV3B8Z.4RX/TQA8EET3.H9M/tron..tion_2ecfac97233d89a0_0001.0000_1cab448ac398cc4a/Ledger.Net.DLL
----------------------------------------
Newtonsoft.Json
    Versão da assemblagem: 12.0.0.0
    Versão Win32: 12.0.3.23909
    CodeBase: file:///C:/Users/daniel.melo/AppData/Local/Apps/2.0/OGMV3B8Z.4RX/TQA8EET3.H9M/tron..tion_2ecfac97233d89a0_0001.0000_1cab448ac398cc4a/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
MessagingToolkit.QRCode
    Versão da assemblagem: 1.3.0.0
    Versão Win32: 1.3.0.0
    CodeBase: file:///C:/Users/daniel.melo/AppData/Local/Apps/2.0/OGMV3B8Z.4RX/TQA8EET3.H9M/tron..tion_2ecfac97233d89a0_0001.0000_1cab448ac398cc4a/MessagingToolkit.QRCode.DLL
----------------------------------------
SimpleBase
    Versão da assemblagem: 1.0.0.0
    Versão Win32: 1.0.0.0
    CodeBase: file:///C:/Users/daniel.melo/AppData/Local/Apps/2.0/OGMV3B8Z.4RX/TQA8EET3.H9M/tron..tion_2ecfac97233d89a0_0001.0000_1cab448ac398cc4a/SimpleBase.DLL
----------------------------------------
netstandard
    Versão da assemblagem: 2.0.0.0
    Versão Win32: 4.8.3752.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Memory
    Versão da assemblagem: 4.0.1.1
    Versão Win32: 4.6.27617.02
    CodeBase: file:///C:/Users/daniel.melo/AppData/Local/Apps/2.0/OGMV3B8Z.4RX/TQA8EET3.H9M/tron..tion_2ecfac97233d89a0_0001.0000_1cab448ac398cc4a/System.Memory.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Versão da assemblagem: 4.0.5.0
    Versão Win32: 4.700.19.46214
    CodeBase: file:///C:/Users/daniel.melo/AppData/Local/Apps/2.0/OGMV3B8Z.4RX/TQA8EET3.H9M/tron..tion_2ecfac97233d89a0_0001.0000_1cab448ac398cc4a/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Runtime
    Versão da assemblagem: 4.1.2.0
    Versão Win32: 4.6.25714.01
    CodeBase: file:///C:/Users/daniel.melo/AppData/Local/Apps/2.0/OGMV3B8Z.4RX/TQA8EET3.H9M/tron..tion_2ecfac97233d89a0_0001.0000_1cab448ac398cc4a/System.Runtime.DLL
----------------------------------------
System.Runtime.Serialization
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.3825.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Security
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
System.Deployment.resources
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Deployment.resources/v4.0_4.0.0.0_pt_b03f5f7f11d50a3a/System.Deployment.resources.dll
----------------------------------------

************** Depuração JIT **************
Para activar a depuração just-in-time (JIT), o ficheiro .config para esta
aplicação ou computador (machine.config) tem de ter o
valor jitDebugging definido na secção system.windows.forms.
A aplicação também tem de ser compilada com a depuração
activada.

Por exemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando a depuração JIT está activada, qualquer excepção não processada
será enviada para o depurador JIT registado no computador
em vez de ser processada por esta caixa de diálogo.

****

**Comment by tronfamily** [comment]
Fixed
