### ISSUE TITLE
TRC10 transactions not showing correctly after Airdroping TRC10 Token

### ISSUE THREAD

**Issue by DanielMelo02** [tronfamily/Desktop-Wallet#23]
After using the Distribute Tool for an TRC Token Airdrop there were 1773 new transfers, the airdrop was correctly done.

But returning to the wallet it only added 33 new trc10 transactions:

![image](https://user-images.githubusercontent.com/44190920/72429609-a9b12a80-3790-11ea-8daa-cefefe7b34df.png)

![image](https://user-images.githubusercontent.com/44190920/72428798-b765b080-378e-11ea-8330-b1c2a04c5d38.png)

**Comment by tronfamily** [comment]
Fixed
