### ISSUE TITLE
Unable to verify transactions after airdrop

### ISSUE THREAD

**Issue by DanielMelo02** [tronfamily/Desktop-Wallet#24]
after an airdrop using the distribute tool this error pops when trying to verify the transactions:

![image](https://user-images.githubusercontent.com/44190920/72448711-c3b23380-37b7-11ea-85e1-0a610bc41a54.png)

Error translation - the chain conversion "Confirmed" for the "Boolean" isn't valid

**Comment by tronfamily** [comment]
fixed
