### ISSUE TITLE
Distribution tool - button overlay

### ISSUE THREAD

**Issue by Test0rMaik** [tronfamily/Desktop-Wallet#25]
Die Buttons überlagern sich, so dass nicht alle Funktionen zugänglich sind.

![distri01](https://user-images.githubusercontent.com/47918413/72467647-a68f5c00-37db-11ea-938b-8fc46d5a78ff.jpg)

**Comment by tronfamily** [comment]
Is the problem still current or can it be closed?

**Comment by Test0rMaik** [comment]
Yes, that error still occours.

**Comment by tronfamily** [comment]
Fixed

**Comment by Test0rMaik** [comment]
Leider noch nicht ganz gefixed:

![distri02](https://user-images.githubusercontent.com/47918413/73972835-c5d46180-4921-11ea-857e-784aebc541cb.jpg)

Ein Button (rechts) wird faktisch ganz verdeckt und scheint bei Vollbild mehr durch, als im nicht maximierten Fenster.

Neuestes Update wurde zuvor installiert.

**Comment by Test0rMaik** [comment]
Issue fixed, thx.
