### ISSUE TITLE
Wallet activation status incorrect

### ISSUE THREAD

**Issue by Test0rMaik** [tronfamily/Desktop-Wallet#26]
Testwallet: TBdrH7fb6YcWu4tmeVZPu7iAmX4Km1B9YJ
Obwohl TRX eingegangen sind und wiederholt freezed und unfreezed sowie gevotet wurde, wird das wallet als inaktiv angezeigt.

![wallet01](https://user-images.githubusercontent.com/47918413/72468192-ddb23d00-37dc-11ea-9525-f601f4ec5d48.jpg)

**Comment by tronfamily** [comment]
Fixed
