### ISSUE TITLE
Doppelte Einträge in Adressbuch

### ISSUE THREAD

**Issue by Ischkur** [tronfamily/Desktop-Wallet#29]
Der Import einer neuen Wallet endet im Erstellen eines neuen Eintrages im Adressbuch. Egal, ob es schon einen Eintrag zu dem Wallet gab oder nicht. 

Ich würde erwarten, dass der bestehende Eintrag im Adressbuch upgedatet wird oder dass der Eintrag so bestehen bleibt, wie er war.

**Comment by tronfamily** [comment]
fixed
