### ISSUE TITLE
BUG: TRC20 incorrect amount

### ISSUE THREAD

**Issue by Test0rMaik** [tronfamily/Desktop-Wallet#3]
Die Anzeige im Dashboard zeigt eine falsche Anzahl der TRC20 an.
![trc20-i01](https://user-images.githubusercontent.com/47918413/72221068-60c26180-3557-11ea-9dfa-d2a8178f6db3.jpg)

Anzeige: 1200
tatsächlich: 12

**Comment by tronfamily** [comment]
Bug in TronAPI.

**Comment by tronfamily** [comment]
You can correct this, if you send this real amount temporary to other wallet.

**Comment by tronfamily** [comment]
Is the problem still current or can it be closed?

**Comment by Test0rMaik** [comment]
Yes, it's still there. Showing 1200 instead of 12

**Comment by tronfamily** [comment]
Fixed.
