### ISSUE TITLE
Request: Exchanges Favorites

### ISSUE THREAD

**Issue by Test0rMaik** [tronfamily/Desktop-Wallet#4]
Wunsch:
Favoriten selektierbar bei allen Exchanges, nicht nur bei Bancor.

**Comment by tronfamily** [comment]
Bancor outdated and ready to remove.

**Comment by Test0rMaik** [comment]
Dieser Wunsch war nicht auf Bancor bezogen, sondern auf alle Exchanges. Siehe initialen Post.

**Comment by tronfamily** [comment]
Added.
