### ISSUE TITLE
missing Filter Exchanges (Orderbook)

### ISSUE THREAD

**Issue by Test0rMaik** [tronfamily/Desktop-Wallet#5]
Es fehlen die Filter beim "Kaufen"-Orderbook, welche beim "Verkaufen"-Orderbook vorhanden sind.
![exchanges01](https://user-images.githubusercontent.com/47918413/72221243-0aeeb900-3559-11ea-93f1-8714b96fe906.jpg)

**Comment by tronfamily** [comment]
Fixed

**Comment by Test0rMaik** [comment]
"Price" und "Amount" Filter fehlen nach wie vor beim Kaufen-Orderbook,

**Comment by tronfamily** [comment]
Fixed.
