### ISSUE TITLE
Crasch nach Abbrechen von Hinzufügen neuer Adresse aus Transaktionsliste

### ISSUE THREAD

**Issue by Ischkur** [tronfamily/Desktop-Wallet#8]
In der Transaktionsliste hat man einen Add Button zum Adden einer Addresse im Address Buch. 
- Click auf ADD
- Dialog erscheint
![image](https://user-images.githubusercontent.com/13943220/72221405-bba98800-355a-11ea-88ec-4aec5d7db0c9.png)
- Cancel Klicken
-> Applikation stürzt ab.

**Zweiter Weg zum Fehler:**
System: 

-- Wallet von Ledger
-- Ledger nicht angeschlossen

Steps to Repoduce:
-- Click auf leere Spalte Add 
![image](https://user-images.githubusercontent.com/13943220/72224225-45b41980-3578-11ea-8cc2-529a6351e81e.png)
-- Im Dialog Cancel klicken
-- Fehlermeldung erscheint -> siehe Kommentar

Erwartetes Verhalten:
- Der Dialog schliesst sich und man kann weiter arbeiten.

**Comment by Ischkur** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Invalid character:  
   at SimpleBase.Base58.Decode(ReadOnlySpan`1 text)
   at SimpleBase.Base58.Decode(String text)
   at TRONFamily_DesktopWallet.Module1.bAddressToH(String adress)
   at TRONFamily_DesktopWallet.Form1.DataGridView5_CellClick(Object sender, DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
TRON-Family Wallet
    Assembly Version: 1.0.1.0
    Win32 Version: 1.0.1.0
    CodeBase: file:///C:/Users/beni/AppData/Local/Apps/2.0/GHT5MG5J.LZ2/7XV4835W.C0J/tron..tion_2ecfac97233d89a0_0001.0000_1cab4489c319bc8a/TRON-Family%20Wallet.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Windows.Forms.DataVisualization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3815.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.DataVisualization/v4.0_4.0.0.0__31bf3856ad364e35/System.Windows.Forms.DataVisualization.dll
----------------------------------------
TRON-Family Wallet.resources
    Assembly Version: 1.0.1.0
    Win32 Version: 1.0.1.0
    CodeBase: file:///C:/Users/beni/AppData/Local/Apps/2.0/GHT5MG5J.LZ2/7XV4835W.C0J/tron..tion_2ecfac97233d89a0_0001.0000_1cab4489c319bc8a/en/TRON-Family%20Wallet.resources.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Users/beni/AppData/Local/Apps/2.0/GHT5MG5J.LZ2/7XV4835W.C0J/tron..tion_2ecfac97233d89a0_0001.0000_1cab4489c319bc8a/Newtonsoft.Json.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.VisualBasic.resources
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic.resources/v4.0_10.0.0.0_de_b03f5f7f11d50a3a/Microsoft.VisualBasic.resources.dll
----------------------------------------
System.Deployment
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
Device.Net
    Assembly Version: 3.1.0.0
    Win32 Version: 3.1.0.0
    CodeBase: file:///C:/Users/beni/AppData/Local/Apps/2.0/GHT5MG5J.LZ2/7XV4835W.C0J/tron..tion_2ecfac97233d89a0_0001.0000_1cab4489c319bc8a/Device.Net.DLL
----------------------------------------
Hid.Net
    Assembly Version: 3.1.0.0
    Win32 Version: 3.1.0.0
    CodeBase: file:///C:/Users/beni/AppData/Local/Apps/2.0/GHT5MG5J.LZ2/7XV4835W.C0J/tron..tion_2ecfac97233d89a0_0001.0000_1cab4489c319bc8a/Hid.Net.DLL
----------------------------------------
Ledger.Net
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.0
    CodeBase: file:///C:/Users/beni/AppData/Local/Apps/2.0/GHT5MG5J.LZ2/7XV4835W.C0J/tron..tion_2ecfac97233d89a0_0001.0000_1cab4489c319bc8a/Ledger.Net.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
MessagingToolkit.QRCode
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Users/beni/AppData/Local/Apps/2.0/GHT5MG5J.LZ2/7XV4835W.C0J/tron..tion_2ecfac97233d89a0_0001.0000_1cab4489c319bc8a/MessagingToolkit.QRCode.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3825.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Tron.Net.Crypto
    Assembly Version: 0.6.0.0
    Win32 Version: 0.6.0.0
    CodeBase: file:///C:/Users/beni/AppData/Local/Apps/2.0/GHT5MG5J.LZ2/7XV4835W.C0J/tron..tion_2ecfac97233d89a0_0001.0000_1cab4489c319bc8a/Tron.Net.Crypto.DLL
----------------------------------------
Tron.Net.Common
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/beni/AppData/Local/Apps/2.0/GHT5MG5J.LZ2/7XV4835W.C0J/tron..tion_2ecfac97233d89a0_0001.0000_1cab4489c319bc8a/Tron.Net.Common.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.27617.02
    CodeBase: file:///C:/Users/beni/AppData/Local/Apps/2.0/GHT5MG5J.LZ2/7XV4835W.C0J/tron..tion_2ecfac97233d89a0_0001.0000_1cab4489c319bc8a/System.Memory.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
SimpleBase
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/beni/AppData/Local/Apps/2.0/GHT5MG5J.LZ2/7XV4835W.C0J/tron..tion_2ecfac97233d89a0_0001.0000_1cab4489c319bc8a/SimpleBase.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.5.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/beni/AppData/Local/Apps/2.0/GHT5MG5J.LZ2/7XV4835W.C0J/tron..tion_2ecfac97233d89a0_0001.0000_1cab4489c319bc8a/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Ischkur** [comment]
Hatte das Problem grad wieder.

**Comment by tronfamily** [comment]
Fixed
