### ISSUE TITLE
missing function (window close)

### ISSUE THREAD

**Issue by Test0rMaik** [tronfamily/Desktop-Wallet#9]
- klicken des Buttons "Vote" 
-> öffnen des Popups "Approve" Disapprove"

Möchte man nun zurück und einfach abbrechen, gibt es einen Zwang "Disapprove" zu tätigen.
Die "ESC"-Taste bietet keine klassische Abbruchfunktion, wie normal bei Programmen üblich.

**Comment by tronfamily** [comment]
Disapprove is the cancel button
